//@ui5-bundle de/itsfullofstars/bingo/bingo/Component-preload.js
sap.ui.require.preload({
	"de/itsfullofstars/bingo/bingo/Component.js":function(){
sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","./model/models"],function(t,e,n){function s(t){return t&&t.__esModule&&typeof t.default!=="undefined"?t.default:t}const i=e["support"];const o=s(n);const a=t.extend("de.itsfullofstars.bingo.bingo.Component",{metadata:{manifest:"json"},init:function e(){t.prototype.init.call(this);this.setModel(o.createDeviceModel(),"device");this.getRouter().initialize()},getContentDensityClass:function t(){if(this.contentDensityClass===undefined){if(document.body.classList.contains("sapUiSizeCozy")||document.body.classList.contains("sapUiSizeCompact")){this.contentDensityClass=""}else if(!i.touch){this.contentDensityClass="sapUiSizeCompact"}else{this.contentDensityClass="sapUiSizeCozy"}}return this.contentDensityClass}});return a});
},
	"de/itsfullofstars/bingo/bingo/controller/App.controller.js":function(){
sap.ui.define(["./BaseController"],function(e){function n(e){return e&&e.__esModule&&typeof e.default!=="undefined"?e.default:e}const t=n(e);const o=t.extend("de.itsfullofstars.bingo.bingo.controller.App",{onInit:function e(){this.getView().addStyleClass(this.getOwnerComponent().getContentDensityClass())}});return o});
},
	"de/itsfullofstars/bingo/bingo/controller/BaseController.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/core/UIComponent","sap/ui/core/routing/History"],function(e,t,n){const o=e.extend("de.itsfullofstars.bingo.bingo.controller.BaseController",{getOwnerComponent:function t(){return e.prototype.getOwnerComponent.call(this)},getRouter:function e(){return t.getRouterFor(this)},getResourceBundle:function e(){const t=this.getOwnerComponent().getModel("i18n");return t.getResourceBundle()},getModel:function e(t){return this.getView().getModel(t)},setModel:function e(t,n){this.getView().setModel(t,n);return this},navTo:function e(t,n,o){this.getRouter().navTo(t,n,undefined,o)},onNavBack:function e(){const t=n.getInstance().getPreviousHash();if(t!==undefined){window.history.go(-1)}else{this.getRouter().navTo("main",{},undefined,true)}}});return o});
},
	"de/itsfullofstars/bingo/bingo/controller/Main.controller.js":function(){
sap.ui.define(["./BaseController","sap/ui/model/json/JSONModel","../model/models","../model/buzzword","sap/ui/core/Fragment","sap/m/library","sap/ui/core/syncStyleClass"],function(e,t,o,s,n,i,l){function r(e){return e&&e.__esModule&&typeof e.default!=="undefined"?e.default:e}const d=r(e);const a=r(o);const c=r(s);const u=d.extend("de.itsfullofstars.bingo.bingo.controller.Main",{onInit:function e(){this.model=a.createViewModel();this.setModel(this.model,"mainView");this.getView().addStyleClass(this.getOwnerComponent().getContentDensityClass());this.prepareLayout();this.buzzwordsModel=this.getOwnerComponent().getModel();this.buzzwordsModel.dataLoaded().then(()=>{this.pickBuzzwords()}).catch(()=>console.log("error"))},prepareLayout:function e(){const t=this.model.getProperty("/rows");const o=this.model.getProperty("/columns");this.elements=t*o;this.calcColumns(o)},navToLegalDisclosure:function e(){const t="https://www.itsfullofstars.de/Impressum";i.URLHelper.redirect(t,true)},navToLicense:function e(){const t="/LICENSE";i.URLHelper.redirect(t,true)},onLegalInfoPress:function e(t){const o=this.getView();const s=t.getSource();if(!this._legalInfoPopover){this._legalInfoPopover=n.load({id:o.getId(),name:"de.itsfullofstars.bingo.bingo.view.fragments.LegalInfo",controller:this}).then(function(e){o.addDependent(e);e.openBy(s);return e})}else{this._legalInfoPopover.then(e=>{if(e.isOpen()){e.close()}else{e.openBy(s)}})}},calcColumns:function e(t){const o=Math.floor(100/t);let s="";for(let e=0;e<t;e++){s+=o.toString()+"% "}const n=this.getModel("mainView");n.setProperty("/columnLayout",s)},onTilePress:function e(t){const o=t.getSource();o.toggleStyleClass("bingoCardSelected")},pickBuzzwords:function e(){if(this.elements<=this.buzzwordsModel.getProperty("/").length){let e=[];e=c.pickBuzzwords(this.buzzwordsModel,this.elements);this.setModel(new t(e),"bingo")}},onSettingsClose:function e(){this._settingsDialog.then(e=>{e.close();this.prepareLayout();this.doReloadBuzzowrds()}).catch(()=>console.log("Error"))},doOpenSettings:function e(){const t=this.getView();if(!this._settingsDialog){this._settingsDialog=n.load({id:t.getId(),name:"de.itsfullofstars.bingo.bingo.view.fragments.Settings",controller:this}).then(e=>{const o=e;t.addDependent(o);o.open();l(this.getOwnerComponent().getContentDensityClass(),this.getView(),o);return o})}else{this._settingsDialog.then(e=>{e.open()}).catch(()=>console.log("Error"))}},doReloadBuzzowrds:function e(){this.buzzwordsModel=new t;this.buzzwordsModel.loadData("./model/buzzwords.json");this.buzzwordsModel.dataLoaded().then(()=>{this.pickBuzzwords()}).catch(()=>console.log("error"));this.resetTileState()},resetTileState:function e(){const t=this.byId("bingoCardGrid");const o=t.getItems();for(let e=0;e<o.length;e++){o[e].removeStyleClass("bingoCardSelected")}}});return u});
},
	"de/itsfullofstars/bingo/bingo/i18n/i18n.properties":'appTitle=SAP Keynote Buzzword Bingo\nappDescription=UI5 Application bingo\neventName=DSAG Technologie Tage 2023\nlegaldisclosure=Legal Disclosure\ncopyrights=Copyright\nsettings=Configuration\nrows=Rows\ncolumns=Columns',
	"de/itsfullofstars/bingo/bingo/i18n/i18n_de.properties":'appTitle=SAP Keynote Buzzword Bingo\nappDescription=UI5 Application bingo\neventName=DSAG Technologie Tage 2023\nlegaldisclosure=Impressum\ncopyrights=Copyright\nsettings=Einstellungen\nrows=Zeilen\ncolumns=Spalten',
	"de/itsfullofstars/bingo/bingo/i18n/i18n_en.properties":'appTitle=SAP Keynote Buzzword Bingo\nappDescription=UI5 Application bingo\neventName=DSAG Technologie Tage 2023\nlegaldisclosure=Legal Disclosure\ncopyrights=Copyright\nsettings=Configuration\nrows=Rows\ncolumns=Columns',
	"de/itsfullofstars/bingo/bingo/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"de.itsfullofstars.bingo.bingo","type":"application","i18n":"i18n/i18n.properties","title":"{{appTitle}}","description":"{{appDescription}}","applicationVersion":{"version":"1.0.0"},"dataSources":{"buzzwords":{"uri":"./model/buzzwords.json","type":"JSON"}}},"sap.ui":{"technology":"UI5","icons":{},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"rootView":{"viewName":"de.itsfullofstars.bingo.bingo.view.App","type":"XML","async":true,"id":"app"},"dependencies":{"minUI5Version":"1.108.5","libs":{"sap.ui.core":{},"sap.ui.layout":{},"sap.ui.unified":{},"sap.m":{}}},"resources":{"css":[{"uri":"css/style.css"}]},"handleValidation":true,"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"de.itsfullofstars.bingo.bingo.i18n.i18n"}},"":{"type":"sap.ui.model.json.JSONModel","dataSource":"buzzwords"}},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"de.itsfullofstars.bingo.bingo.view","controlId":"app","controlAggregation":"pages","async":true},"routes":[{"pattern":"","name":"main","target":"main"}],"targets":{"main":{"viewId":"main","viewName":"Main"}}}}}',
	"de/itsfullofstars/bingo/bingo/model/buzzword.js":function(){
sap.ui.define([],function(){var r={pickBuzzwords(r,t){const e=[];for(let n=0;n<t;n++){e.push(this.pickSingleBuzzword(r))}return e},pickSingleBuzzword(r){const t=r.getProperty("/");const e=Math.floor(Math.random()*t.length);const n=t.splice(e,1)[0];r.setProperty("/",t);return n}};return r});
},
	"de/itsfullofstars/bingo/bingo/model/models.js":function(){
sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/model/BindingMode","sap/ui/Device"],function(e,n,o){var s={createDeviceModel:()=>{const s=new e(o);s.setDefaultBindingMode(n.OneWay);return s},createViewModel:()=>{const n={rows:o.system.phone?4:5,maxRows:o.system.phone?5:8,columns:o.system.phone?4:5,maxColumns:o.system.phone?5:8,rowLayout:"20% 20% 20% 20% 20%",columnLayout:"20% 20% 20% 20% 20%"};const s=new e(n);return s}};return s});
},
	"de/itsfullofstars/bingo/bingo/model/types.js":function(){

},
	"de/itsfullofstars/bingo/bingo/view/App.view.xml":'<mvc:View\n\tcontrollerName="de.itsfullofstars.bingo.bingo.controller.App"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"><App id="app" /></mvc:View>',
	"de/itsfullofstars/bingo/bingo/view/Main.view.xml":'<mvc:View\n\tcontrollerName="de.itsfullofstars.bingo.bingo.controller.Main"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:grid="sap.ui.layout.cssgrid"\n\txmlns:f="sap.f"\n\txmlns:mvc="sap.ui.core.mvc"><Page\n\t\ttitle="{i18n>appTitle}"><headerContent><Button id="doSettings" icon="sap-icon://settings" type="Transparent" press="doOpenSettings" /><Button id="doReloadData" icon="sap-icon://refresh" type="Transparent" press="doReloadBuzzowrds" /><Button id="legalMenu" icon="sap-icon://compare" tooltip="{i1n>legalInfo}" type="Transparent" press="onLegalInfoPress"><layoutData><OverflowToolbarLayoutData closeOverflowOnInteraction="false"/></layoutData></Button></headerContent><content><VBox class="responsiveMargin"><grid:CSSGrid\n\t\t\t\t\tid="bingoCardGrid"\n\t\t\t\t\titems="{bingo>/}"\n\t\t\t\t\tclass="responsiveMargin"\t\t\t\t\n\t\t\t\t\tgridTemplateColumns="{mainView>/columnLayout}"\n\t\t\t\t\tgridGap="0.3em"\n\t\t\t\t\t><GenericTile class="" \n\t\t\t\t\t\twidth="auto"\n\t\t\t\t\t\tsizeBehavior="Responsive"\n\t\t\t\t\t\tpress="onTilePress"><TileContent class="sapUiNoMargin noMinWidth"><Text\n\t\t\t\t\t\t\t\ttext="{bingo>value}"\n\t\t\t\t\t\t\t\tclass="sapUiNoMargin"\n\t\t\t\t\t\t\t\twidth="100%"\n\t\t\t\t\t\t\t\ttextAlign="Center"\n\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\twrapping="true"\n\t\t\t\t\t\t\t\twrappingType="Hyphenated"\n\t\t\t\t\t\t\t\t /></TileContent></GenericTile></grid:CSSGrid></VBox></content><footer><OverflowToolbar><ToolbarSpacer/><Text text="{i18n>eventName}" /></OverflowToolbar></footer></Page></mvc:View>',
	"de/itsfullofstars/bingo/bingo/view/fragments/LegalInfo.fragment.xml":'<core:FragmentDefinition \r\n\txmlns="sap.m" \r\n\txmlns:core="sap.ui.core" \r\n\txmlns:mvc="sap.ui.core.mvc" \r\n\txmlns:l="sap.ui.layout"\r\n\t><ActionSheet \r\n\t\txmlns="sap.m" \r\n\t\txmlns:core="sap.ui.core" \r\n\t\tshowCancelButton="true" \r\n\t\tplacement="Bottom" ><Button text="{i18n>legaldisclosure}" class="sapUiSizeCompact" icon="sap-icon://role" press="navToLegalDisclosure"/><Button text="{i18n>license}" class="sapUiSizeCompact" icon="sap-icon://co" press="navToLicense"/></ActionSheet></core:FragmentDefinition>',
	"de/itsfullofstars/bingo/bingo/view/fragments/Settings.fragment.xml":'<core:FragmentDefinition \r\n\txmlns="sap.m" \r\n\txmlns:core="sap.ui.core" \r\n\txmlns:mvc="sap.ui.core.mvc" \r\n\t><Dialog\r\n\t\tid="settingsDialog"\r\n\t\ttitle="{i18n>settings}"\r\n\t\ttype="Message"><content><List id="idSettingsList"><InputListItem label="{i18n>rows}" ><StepInput\r\n\t\t\t\t\t\tvalue="{mainView>/rows}"\r\n\t\t\t\t\t\tdisplayValuePrecision="{displayValuePrecision}"\r\n\t\t\t\t\t\tmin="3"\r\n\t\t\t\t\t\tmax="{mainView>/maxRows}"\r\n\t\t\t\t\t\twidth="10rem"\r\n\t\t\t\t\t\tlargerStep="1"/></InputListItem><InputListItem label="{i18n>columns}"><StepInput\r\n\t\t\t\t\t\tvalue="{mainView>/columns}"\r\n\t\t\t\t\t\tdisplayValuePrecision="{displayValuePrecision}"\r\n\t\t\t\t\t\tmin="3"\r\n\t\t\t\t\t\tmax="{mainView>/maxColumns}"\r\n\t\t\t\t\t\twidth="10rem"\r\n\t\t\t\t\t\tlargerStep="1"/></InputListItem></List></content><beginButton><Button \r\n\t\t\t\ttype="Emphasized"\r\n\t\t\t\ttext="OK"\r\n\t\t\t\tpress="onSettingsClose"\r\n\t\t\t\t></Button></beginButton></Dialog></core:FragmentDefinition>'
});
//# sourceMappingURL=Component-preload.js.map
